### ISSUE TITLE
Error generating changelog with views

### ISSUE THREAD

**Issue by JeremyDel** [liquibase/liquibase-databricks#115]
When generating a changelog that contains a new view definition I get the following error:

[2024-03-19 16:08:04] SEVERE [liquibase.integration] java.lang.NullPointerException
liquibase.exception.CommandExecutionException: java.lang.NullPointerException
        at liquibase.command.CommandScope.execute(CommandScope.java:253)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:390)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:171)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:365)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:171)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:362)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:102)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:116)
Caused by: java.lang.NullPointerException
        at liquibase.ext.databricks.snapshot.jvm.ViewSnapshotGeneratorDatabricks.snapshotObject(ViewSnapshotGeneratorDatabricks.java:62)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:65)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:68)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:313)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:456)
        at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:478)
        at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:369)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:332)
        at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:106)
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:37)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:216)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:189)
        at liquibase.command.core.DiffCommandStep.generateDatabaseShapshot(DiffCommandStep.java:205)
        at liquibase.command.core.DiffCommandStep.createReferenceSnapshot(DiffCommandStep.java:192)
        at liquibase.command.core.DiffCommandStep.createDiffResult(DiffCommandStep.java:113)
        at liquibase.command.core.DiffCommandStep.run(DiffCommandStep.java:89)
        at liquibase.command.CommandScope.execute(CommandScope.java:217)
        
I have managed to replicate the error multiple times and whenever i add a view in my schema the generate-changelog/diffChangeLog/diff command fails immediatly. 
 
I've liquibase 4.26.0 and installed liquibase-databricks-1.1.3 and the latest Databricsk JDBC jar files.

**Comment by Shahrukh-ali-lodhi** [comment]
@JeremyDel, have you been able to generate a change log without views, only for tables?

**Comment by JeremyDel** [comment]
Yes it works only for tables, whenever i create a view statement on my schema i get this error. 
I have tested multiple version of my JDBC driver for databricks but i still have the error.

**Comment by Shahrukh-ali-lodhi** [comment]
For me, it's not working even for tables. I'm using all the latest libraries and using databricks cluster not databricks warehouse.
